---
  - include_tasks: schema.yml
    with_items:
      - name: Mail
        file: schema.ldif
        checkattr: postfixConfiguration

  - name: Create Postfix configuration object
    run_once: true
    ldap_entry:
      dn: "cn={{ ldapmail_postfix_cfg_cn }},{{ ldapmail_ldap_base }}"
      server_uri: "{{ ldapmail_ldap_ansible_url }}"
      bind_dn: "{{ ldapmail_bind_dn }}"
      bind_pw: "{{ ldapmail_bind_pwd }}"
      objectClass:
        - top
        - postfixConfiguration
      attributes:
        cn: "{{ ldapmail_postfix_cfg_cn }}"

  - name: Configure Postfix virual domains
    run_once: true
    ldap_attr:
      dn: "cn={{ ldapmail_postfix_cfg_cn }},{{ ldapmail_ldap_base }}"
      server_uri: "{{ ldapmail_ldap_ansible_url }}"
      bind_dn: "{{ ldapmail_bind_dn }}"
      bind_pw: "{{ ldapmail_bind_pwd }}"
      name: virtualDomain
      values: "{{ ldapmail_postfix_virtual_domains }}"

  - name: Create user configuration files
    become: True
    with_items: "{{ ldapmail_mail_users }}"
    template:
      src: mailuser.ldif.j2
      dest: "/etc/ldap/ansible/mail-{{ item.id }}.ldif"
      owner: root
      group: root
      mode: 0640

  - name: Apply user configuration files
    become: True
    with_items: "{{ ldapmail_mail_users }}"
    shell: /usr/bin/ldapmodify -Z -x -D '{{ ldapmail_bind_dn }}' -w '{{ ldapmail_bind_pwd }}' -H "{{ ldapmail_ldap_url }}" < /etc/ldap/ansible/mail-{{ item.id }}.ldif
    failed_when: False
    changed_when: False

  - name: Configure user aliases
    run_once: true
    with_items: "{{ ldapmail_mail_users }}"
    when: item.aliases is defined
    ldap_attr:
      dn: "uid={{ item.id }},ou=Users,{{ ldapmail_ldap_base }}"
      server_uri: "{{ ldapmail_ldap_ansible_url }}"
      bind_dn: "{{ ldapmail_bind_dn }}"
      bind_pw: "{{ ldapmail_bind_pwd }}"
      name: alias
      values: "{{ item.aliases }}"

  - name: Configure user send aliases
    run_once: true
    with_items: "{{ ldapmail_mail_users }}"
    when: item.sendAliases is defined
    ldap_attr:
      dn: "uid={{ item.id }},ou=Users,{{ ldapmail_ldap_base }}"
      server_uri: "{{ ldapmail_ldap_ansible_url }}"
      bind_dn: "{{ ldapmail_bind_dn }}"
      bind_pw: "{{ ldapmail_bind_pwd }}"
      name: sendAlias
      values: "{{ item.sendAliases }}"

  - name: Configure user quota
    run_once: true
    with_items: "{{ ldapmail_mail_users }}"
    ldap_attr:
      dn: "uid={{ item.id }},ou=Users,{{ ldapmail_ldap_base }}"
      server_uri: "{{ ldapmail_ldap_ansible_url }}"
      bind_dn: "{{ ldapmail_bind_dn }}"
      bind_pw: "{{ ldapmail_bind_pwd }}"
      name: mailboxQuota
      values: '{{ item.mailboxQuota|default("*:storage="+ ldapmail_default_quota) }}'

  - name: Configure user external send permissons
    run_once: true
    with_items: "{{ ldapmail_mail_users }}"
    ldap_attr:
      dn: "uid={{ item.id }},ou=Users,{{ ldapmail_ldap_base }}"
      server_uri: "{{ ldapmail_ldap_ansible_url }}"
      bind_dn: "{{ ldapmail_bind_dn }}"
      bind_pw: "{{ ldapmail_bind_pwd }}"
      name: canSendExternally
      values: '{{ item.canSendExternally|default("TRUE") }}'

  - name: Configure user external receive permissons
    run_once: true
    with_items: "{{ ldapmail_mail_users }}"
    ldap_attr:
      dn: "uid={{ item.id }},ou=Users,{{ ldapmail_ldap_base }}"
      server_uri: "{{ ldapmail_ldap_ansible_url }}"
      bind_dn: "{{ ldapmail_bind_dn }}"
      bind_pw: "{{ ldapmail_bind_pwd }}"
      name: canReceiveExternally
      values: '{{ item.canReceiveExternally|default("TRUE") }}'

  - name: Configure user mailbox transport
    run_once: true
    with_items: "{{ ldapmail_mail_users }}"
    ldap_attr:
      dn: "uid={{ item.id }},ou=Users,{{ ldapmail_ldap_base }}"
      server_uri: "{{ ldapmail_ldap_ansible_url }}"
      bind_dn: "{{ ldapmail_bind_dn }}"
      bind_pw: "{{ ldapmail_bind_pwd }}"
      name: mailboxTransport
      values: "{{ item.mailboxTransport|default(ldapmail_default_transport) }}"

  - name: Create system users
    run_once: true
    with_items: "{{ ldapmail_system_mail_users }}"
    ldap_entry:
      server_uri: "{{ ldapmail_ldap_ansible_url }}"
      bind_dn: "{{ ldapmail_bind_dn }}"
      bind_pw: "{{ ldapmail_bind_pwd }}"
      dn: "uid={{ item }},ou=Users,{{ ldapmail_ldap_base }}"
      objectClass: systemMailbox
      attributes:
        uid: "{{ item }}"
        primaryMail: "{{ item }}@{{ ldapmail_mail_base }}"
        mailboxQuota: '*:storage=10GB'
        canSendExternally: 'FALSE'
        canReceiveExternally: 'FALSE'
        mailboxTransport: 'lmtp:unix:private/dovecot-lmtp'
